# Generated by Django 3.2.4 on 2021-07-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Group',
            fields=[
                ('student_group_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_group', verbose_name='group_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_fk')),
            ],
            options={
                'verbose_name': 'student_group',
                'verbose_name_plural': 'student_groups',
                'db_table': 'STUDENT_GROUP',
            },
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('cgpa', models.FloatField(blank=True, default=None, null=True)),
                ('bio', models.TextField(blank=True, default=None, null=True)),
                ('skills', models.TextField(blank=True, default=None, null=True)),
                ('participations', models.TextField(blank=True, default=None, null=True)),
                ('social_media_links', models.TextField(blank=True, default=None, null=True)),
                ('interests', models.TextField(blank=True, default=None, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student_fk')),
            ],
            options={
                'verbose_name': 'student_profile',
                'verbose_name_plural': 'student_profiles',
                'db_table': 'STUDENT_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Student_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa', models.FloatField(blank=True, default=None, null=True)),
                ('cgpa', models.FloatField(blank=True, default=None, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.semester', verbose_name='semester_fk')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_group', verbose_name='student_group_fk')),
            ],
            options={
                'verbose_name': 'student_result',
                'verbose_name_plural': 'student_results',
                'db_table': 'STUDENT_RESULT',
            },
        ),
        migrations.CreateModel(
            name='Student_Quiz_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default=None, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_data', verbose_name='quiz_data_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_fk')),
            ],
            options={
                'verbose_name': 'student_quiz_answers',
                'verbose_name_plural': 'student_quiz_answers',
                'db_table': 'STUDENET_QUIZ_ANSWER',
            },
        ),
        migrations.CreateModel(
            name='Student_Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_time', models.DateTimeField(auto_now=True)),
                ('marks', models.FloatField(blank=True, default=0, null=True)),
                ('attempt_count', models.IntegerField(blank=True, default=0, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='quiz_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_fk')),
            ],
            options={
                'verbose_name': 'student_quiz',
                'verbose_name_plural': 'student_quizes',
                'db_table': 'STUDENET_QUIZ',
            },
        ),
        migrations.CreateModel(
            name='Student_Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_profile', verbose_name='student_profile_fk')),
            ],
            options={
                'verbose_name': 'student_project_relation',
                'verbose_name_plural': 'student_project_relations',
                'db_table': 'STUDENT_PROJECT',
            },
        ),
        migrations.CreateModel(
            name='Student_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student_fk')),
            ],
            options={
                'verbose_name': 'student_experience',
                'verbose_name_plural': 'student_experiences',
                'db_table': 'STUDENT_EXPERIENCE',
            },
        ),
        migrations.CreateModel(
            name='Student_Current_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(blank=True, default=None, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.semester', verbose_name='semester_fk')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_group', verbose_name='student_group_fk')),
            ],
            options={
                'verbose_name': 'student_current_info',
                'verbose_name_plural': 'student_current_infos',
                'db_table': 'STUDENT_CURRENT_INFO',
            },
        ),
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.course', verbose_name='course_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_fk')),
            ],
            options={
                'verbose_name': 'student_course_relation',
                'verbose_name_plural': 'student_course_relations',
                'db_table': 'STUDENT_COURSE',
            },
        ),
    ]
