# Generated by Django 3.2.4 on 2021-07-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210713_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_project',
            options={'verbose_name': 'student_project', 'verbose_name_plural': 'student_projects'},
        ),
    ]
