# Generated by Django 3.2 on 2021-07-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210712_2237'),
        ('student', '0004_auto_20210712_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='student_current_info',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_current_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_current_info',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='student_experience',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_experience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_experience',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='student_project',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_project',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='student_quiz',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_quiz',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='student_quiz_answers',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_quiz_answers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_quiz_answers',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='student_result',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='student_result',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_result',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
    ]
