# Generated by Django 3.2.4 on 2021-07-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_auto_20210708_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_marks', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('grp_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizes',
                'db_table': 'QUIZ',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Data',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=450)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='quiz_fk')),
            ],
            options={
                'verbose_name': 'quiz_data',
                'verbose_name_plural': 'quiz_data',
                'db_table': 'QUIZ_Data',
            },
        ),
    ]
