# Generated by Django 3.2.4 on 2021-07-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('total_marks', models.FloatField(blank=True, default=None, null=True)),
                ('total_questions', models.IntegerField(blank=True, default=None, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('duration', models.DurationField(blank=True, default=None, null=True)),
                ('max_attempts', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'db_table': 'QUIZ',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Data',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, default=None, null=True)),
                ('question_img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('options', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer', models.TextField(blank=True, default=None, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='quiz_fk')),
            ],
            options={
                'verbose_name': 'quiz_data',
                'verbose_name_plural': 'quiz_data',
                'db_table': 'QUIZ_Data',
            },
        ),
        migrations.CreateModel(
            name='Group_Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('grp_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='quiz_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_fk')),
            ],
            options={
                'verbose_name': 'quiz_group',
                'verbose_name_plural': 'quiz_groups',
                'db_table': 'QUIZ_GROUP',
            },
        ),
    ]
