# Generated by Django 3.2.4 on 2021-07-11 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0004_alter_user_role'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='teacher_fk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz_data',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quiz_data',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz_data',
            name='options',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Group_Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='assignment_fk')),
                ('grp_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_fk')),
            ],
            options={
                'verbose_name': 'quiz_group',
                'verbose_name_plural': 'quiz_groups',
                'db_table': 'QUIZ_ASSIGNMENT',
            },
        ),
    ]
