# Generated by Django 3.2.4 on 2021-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210713_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='desc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
