# Generated by Django 2.2 on 2021-07-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210711_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_quiz',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
