# Generated by Django 3.2 on 2021-07-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210712_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_quiz',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='quiz_fk'),
        ),
    ]
