# Generated by Django 3.2.4 on 2021-07-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210719_1831'),
        ('quiz', '0004_group_quiz_course_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_quiz',
            name='course_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.course_unit', verbose_name='course_unit_fk'),
        ),
    ]
