# Generated by Django 3.2 on 2021-07-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_group_quiz_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_data',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='quiz_data',
            name='school',
        ),
    ]
