# Generated by Django 3.2.4 on 2021-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email Address')),
                ('f_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('staff', models.BooleanField(default=False, verbose_name='Staff Member')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active User')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('role', models.IntegerField(help_text='Teacher_role : 0 and Student_role : 1', verbose_name='Role of user')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'USER',
            },
        ),
    ]
