# Generated by Django 3.2 on 2021-07-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210713_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='school',
        ),
        migrations.AlterField(
            model_name='user_group',
            name='group_name',
            field=models.CharField(max_length=200),
        ),
    ]
