# Generated by Django 3.2.4 on 2021-07-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210708_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_info',
        ),
    ]
