# Generated by Django 3.2.4 on 2021-07-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_delete_admin_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, help_text='Teacher_role : 1 and Student_role : 0', null=True, verbose_name='Role of user'),
        ),
    ]
