# Generated by Django 3.2.4 on 2021-07-19 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210713_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Unit',
            fields=[
                ('course_unit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Course Unit', max_length=500, null=True, verbose_name='Course Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Course Description')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.course', verbose_name='course_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
            ],
            options={
                'verbose_name': 'course unit',
                'verbose_name_plural': 'course units',
                'db_table': 'COURSE_UNIT',
            },
        ),
    ]
