# Generated by Django 3.2.4 on 2021-08-02 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210719_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_unit',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course_unit',
            name='group_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(choices=[(0, 'ABSENT'), (1, 'PRESENT')], default=0)),
                ('group_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='grp_course_fk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_prn')),
            ],
        ),
    ]
