# Generated by Django 2.2 on 2021-07-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210712_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_course',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='group_course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.School', verbose_name='school_fk'),
        ),
    ]
