# Generated by Django 3.2.4 on 2021-08-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210802_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
