# Generated by Django 3.2 on 2021-07-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_semester',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='branch_semester',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk'),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk'),
        ),
    ]
