# Generated by Django 3.2.4 on 2021-07-11 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('min_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'db_table': 'ASSIGNMENT',
            },
        ),
        migrations.CreateModel(
            name='Group_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='assignment_fk')),
                ('grp_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_fk')),
            ],
            options={
                'verbose_name': 'group_assignment',
                'verbose_name_plural': 'group_assignments',
                'db_table': 'GROUP_ASSIGNMENT',
            },
        ),
        migrations.CreateModel(
            name='Assignment_submission',
            fields=[
                ('assignment_submission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='assignment_fk')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='prn_fk')),
            ],
            options={
                'verbose_name': 'assignment_submission',
                'verbose_name_plural': 'assignment_submissions',
                'db_table': 'ASSIGNMENT_SUBMISSION',
            },
        ),
        migrations.CreateModel(
            name='Assignment_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('assignment_submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment_submission', verbose_name='assignment_submission_fk')),
            ],
            options={
                'verbose_name': 'assignment_marks',
                'verbose_name_plural': 'assignment_marks',
                'db_table': 'ASSIGNMENT_MARKS',
            },
        ),
    ]
