# Generated by Django 3.2.4 on 2021-07-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('min_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('max_marks', models.IntegerField(blank=True, default=None, null=True)),
                ('post_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'db_table': 'ASSIGNMENT',
            },
        ),
        migrations.CreateModel(
            name='Group_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='assignment_fk')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('grp_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_fk')),
            ],
            options={
                'verbose_name': 'group_assignment',
                'verbose_name_plural': 'group_assignments',
                'db_table': 'GROUP_ASSIGNMENT',
            },
        ),
        migrations.CreateModel(
            name='Assignment_submission',
            fields=[
                ('assignment_submission_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='assignment_fk')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='prn_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
            ],
            options={
                'verbose_name': 'assignment_submission',
                'verbose_name_plural': 'assignment_submissions',
                'db_table': 'ASSIGNMENT_SUBMISSION',
            },
        ),
        migrations.CreateModel(
            name='Assignment_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, default=0, null=True)),
                ('review', models.TextField(blank=True, default=None, null=True)),
                ('assignment_submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment_submission', verbose_name='assignment_submission_fk')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
            ],
            options={
                'verbose_name': 'assignment_marks',
                'verbose_name_plural': 'assignment_marks',
                'db_table': 'ASSIGNMENT_MARKS',
            },
        ),
    ]
