# Generated by Django 3.2.4 on 2021-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_assignment_post_date'),
        ('assignment', '0004_group_assignment_course_unit'),
    ]

    operations = [
    ]
