# Generated by Django 3.2.4 on 2021-07-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210719_1831'),
        ('assignment', '0005_merge_20210719_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='visibility',
            field=models.CharField(blank=True, choices=[('Hidden', 0), ('Visible', 1), ('Submitable', 2)], default=('Hidden', 0), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group_assignment',
            name='course_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.course_unit', verbose_name='course_unit_fk'),
        ),
    ]
