# Generated by Django 3.2.4 on 2021-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20210720_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='visibility',
            field=models.CharField(blank=True, choices=[('Hidden', 'Hidden'), ('Visible', 'Visible'), ('Submitable', 'Submitable')], default=('Hidden', 'Hidden'), max_length=100, null=True),
        ),
    ]
