# Generated by Django 3.2.4 on 2021-07-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_alter_group_assignment_course_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='visibility',
            field=models.CharField(choices=[('Hidden', 'Hidden'), ('Visible', 'Visible'), ('Submitable', 'Submitable')], default=('Hidden', 'Hidden'), max_length=100),
        ),
    ]
