# Generated by Django 3.2.4 on 2021-07-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_alter_assignment_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='visibility',
            field=models.CharField(blank=True, choices=[('Hidden', 'Hidden'), ('Visible', 'Visible'), ('Submitable', 'Submitable')], default='Hidden', max_length=100, null=True),
        ),
    ]
