# Generated by Django 3.2.4 on 2021-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_alter_assignment_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='submit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
