# Generated by Django 3.2.4 on 2021-07-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('bio', models.TextField(blank=True, default=None, null=True)),
                ('skills', models.TextField(blank=True, default=None, null=True)),
                ('participations', models.TextField(blank=True, default=None, null=True)),
                ('social_media_links', models.TextField(blank=True, default=None, null=True)),
                ('interests', models.TextField(blank=True, default=None, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_fk')),
            ],
            options={
                'verbose_name': 'teacher_profile',
                'verbose_name_plural': 'teacher_profiles',
                'db_table': 'TEACHER_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Teacher_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student_fk')),
            ],
            options={
                'verbose_name': 'teacher_experience',
                'verbose_name_plural': 'teacher_experiences',
                'db_table': 'TEACHER_EXPERIENCE',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Course',
            fields=[
                ('teacher_course_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('group_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_fk')),
            ],
            options={
                'verbose_name': 'teacher_course',
                'verbose_name_plural': 'teacher_courses',
                'db_table': 'TEACHER_COURSE',
            },
        ),
    ]
