# Generated by Django 3.2.4 on 2021-07-09 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0002_auto_20210708_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Course',
            fields=[
                ('teacher_course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('group_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group_course', verbose_name='group_course_fk')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_fk')),
            ],
            options={
                'verbose_name': 'teacher_course',
                'verbose_name_plural': 'teacher_courses',
                'db_table': 'TEACHER_COURSE',
            },
        ),
    ]
