# Generated by Django 3.2.4 on 2021-07-11 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0004_alter_user_role'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('bio', models.TextField()),
                ('skills', models.TextField()),
                ('participations', models.TextField()),
                ('social_media_links', models.TextField()),
                ('interests', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_fk')),
            ],
            options={
                'verbose_name': 'teacher_profile',
                'verbose_name_plural': 'teacher_profiles',
                'db_table': 'TEACHER_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Teacher_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.branch', verbose_name='branch_fk')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.school', verbose_name='school_fk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student_fk')),
            ],
            options={
                'verbose_name': 'teacher_experience',
                'verbose_name_plural': 'teacher_experiences',
                'db_table': 'TEACHER_EXPERIENCE',
            },
        ),
    ]
