# Generated by Django 3.2.4 on 2021-08-04 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0007_delete_attendance'),
        ('teacher', '0002_alter_teacher_course_teacher_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_course',
            name='course_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.course_unit', verbose_name='course_unit_fk'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.IntegerField(blank=True, default=None, null=True)),
                ('topic', models.TextField(blank=True, default=None, null=True)),
                ('tlo_no', models.IntegerField(blank=True, default=None, null=True)),
                ('co_no', models.IntegerField(blank=True, default=None, null=True)),
                ('date_of_plan', models.DateField(blank=True, default=None, null=True)),
                ('date_of_conduction', models.DateField(blank=True, default=None, null=True)),
                ('group_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.group_course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(choices=[(0, 'ABSENT'), (1, 'PRESENT')], default=0)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_prn')),
            ],
        ),
    ]
