# Generated by Django 3.2.4 on 2021-08-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20210804_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='group_course',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='val',
            field=models.IntegerField(choices=[(0, 'ABSENT'), (1, 'PRESENT')], default=1),
        ),
    ]
